version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      TZ: Asia/Tokyo

  db-sandbox:
    image: mysql:5.7
    ports:
      - "3316:3306"
    volumes:
      - db-sandbox-volume:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      TZ: UTC

  memcached:
    image: memcached:1.6.6-alpine
    ports:
      - "11211:11211"

  redis:
    image: redis:6.0.1-alpine3.11
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq

volumes:
  db-volume:
  db-sandbox-volume:
  redis-volume:
  rabbitmq-volume:
