version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      TZ: Asia/Tokyo

  redis:
    image: redis:6.0.1-alpine3.11
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

  memcached:
    image: memcached:1.6.6-alpine
    ports:
      - "11211:11211"

  redisCommander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=redis

volumes:
  db-volume:
  redis-volume:
